### ISSUE TITLE
Issue with writing out subsetted SNP dataset

### ISSUE THREAD

**Issue by jrkirk61** [michaelplynch/demuxSNP#11]
I ran into an issue with writing out the `commonvariants_1kgenomes_subset` object to a file. I see that it's a CollapsedVCF class belonging to the VariantAnnotation package. Within the VariantAnnotation package there is a function `WriteVcf()` that allows me to write this VCF object to a file. The issue is that `WriteVcf()` is supposed to auto-detect the correct assembly, but seems to instead assume that this VCF object is from the old b37 assembly and adds that to the header along with the old scaffold names (see example below). Is there any way that you can edit the `commonvariants_1kgenomes_subset` object so that `WriteVcf()` detects the correct assembly (hg38)? If not, is there an alternative to using this function to write out the VCF to file?

> ##fileformat=VCFv4.1
> ##fileDate=20231201
> ##reference=ftp://ftp.1000genomes.ebi.ac.uk//vol1/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz
> ##source=1000GenomesPhase3Pipeline
> ##FILTER=<ID=PASS,Description="All filters passed">
> ##contig=<ID=1,assembly=b37,length=249250621>
> ##contig=<ID=2,assembly=b37,length=243199373>
> ##contig=<ID=3,assembly=b37,length=198022430>
> ##contig=<ID=4,assembly=b37,length=191154276>
> ##contig=<ID=5,assembly=b37,length=180915260>
> ##contig=<ID=6,assembly=b37,length=171115067>
> ##contig=<ID=7,assembly=b37,length=159138663>
> ##contig=<ID=8,assembly=b37,length=146364022>
> ##contig=<ID=9,assembly=b37,length=141213431>
> ##contig=<ID=10,assembly=b37,length=135534747>
> ##contig=<ID=11,assembly=b37,length=135006516>
> ##contig=<ID=12,assembly=b37,length=133851895>
> ##contig=<ID=13,assembly=b37,length=115169878>
> ##contig=<ID=14,assembly=b37,length=107349540>
> ##contig=<ID=15,assembly=b37,length=102531392>
> ##contig=<ID=16,assembly=b37,length=90354753>
> ##contig=<ID=17,assembly=b37,length=81195210>
> ##contig=<ID=18,assembly=b37,length=78077248>
> ##contig=<ID=19,assembly=b37,length=59128983>
> ##contig=<ID=20,assembly=b37,length=63025520>
> ##contig=<ID=21,assembly=b37,length=48129895>
> ##contig=<ID=22,assembly=b37,length=51304566>
> ##contig=<ID=GL000191.1,assembly=b37,length=106433>
> ##contig=<ID=GL000192.1,assembly=b37,length=547496>
> ##contig=<ID=GL000193.1,assembly=b37,length=189789>
> ##contig=<ID=GL000194.1,assembly=b37,length=191469>
> ##contig=<ID=GL000195.1,assembly=b37,length=182896>
> ##contig=<ID=GL000196.1,assembly=b37,length=38914>
> ##contig=<ID=GL000197.1,assembly=b37,length=37175>
> ##contig=<ID=GL000198.1,assembly=b37,length=90085>
> ...

Thank you!
Jessica

**Comment by michaelplynch** [comment]
Hi Jessica,
If your question is specifically asking about how to get the pipeline working, this shouldn't impact downstream steps. This vcf is indeed based on the GRCh38 assembly (can check with `genome(commonvariants_1kgenomes_subset)` and it should run without issue with VarTrix despite saying its using the b37 assembly in the header.
If your question is purely about changing the header, if you dig into the object a little, the assembly information in the header can be found here: `commonvariants_1kgenomes_subset@metadata$header@header$contig$assembly`
And can be changed manually, e.g.:
`commonvariants_1kgenomes_subset@metadata$header@header$contig$assembly<-"GRCh38"`

Best,
Michael

**Comment by jrkirk61** [comment]
Hi Micheal,

Thanks for letting me know how to change it manually. I'm not trying to run the pipeline, but a client of mine is. She ran into an issue where her VCF file wasn't matching her reference genome files and she needed me to fix it. So one of my initial theories was that the VCF was from different assembly because b37 and all its unique scaffolds were present in the header of the GTF she provided. This of course did not end up being the problem, but it took awhile to resolve that.  So my main goal with this post was to suggest that the true genome information explicitly be in the `commonvariants_1kgenomes_subset` object to avoid others running into the same confusion, especially if they end up using other packages, like `VariantAnnotation`, with it that may do unexpected things (like assuming b37 by default).

Kind regards,
Jessica
