### ISSUE TITLE
Compatibility with cellsnp-lite results?

### ISSUE THREAD

**Issue by mdmanurung** [michaelplynch/demuxSNP#12]
Dear author,

Is it possible to use this package with cellsnp-lite output? I am not sure which object that would be equivalent with vartrix's output.

Thanks in advance!

**Comment by michaelplynch** [comment]
Hi Mikhael,
demuxSNPs reassignment is developed around the output of varTrix's consensus mode, which I don't believe cellsnp-lite has an equivalent.
varTrix describes the consensus mode output as: 

> --scoring-method (-s): The scoring method to be used in the output matrix. In the default consensus mode, the matrix will have a 0 if no reads cover the variant, 1 if all reads at the position support the ref allele, a 2 if one or more reads support the alt allele, and a 3 if one or more reads support both the alt and the ref allele.

You could potentially try converting the cellsnp output based on this, but this isn't something that has been tested.
